#use_frameworks!

target 'EAnalytics_Example' do
  pod 'EAnalytics', :path => '../'

  target 'EAnalytics_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end

target 'EAnalytics_ExampleTV' do
    pod 'EAnalytics', :path => '../'
    
end
