use_frameworks!

target 'Demo Objc' do
  platform :ios, '9.0'
  pod 'EAnalytics', :path => '../'
end

target 'Demo Objc TV' do
  platform :tvos, '9.0'
  pod 'EAnalytics', :path => '../'
end

target 'Demo Swift' do
  platform :ios, '9.0'
  pod 'EAnalytics', :path => '../'
end
